### PR TITLE
add refresh button

### PR DESCRIPTION
**Pull request by markizenlee**

### CODE REVIEW

**Review by JonasonWu — APPROVED** [review]
LGTM

**Comment by JonasonWu** [comment]
Added "<span>=§=</span>" to act as separator. Not tested, so unsure of whether it works out. Maybe merge, then check if the deployment works out? If not, then revert?

**Comment by blin007** [comment]
The divider is messed up, I'm going to fix it

**Review by JonasonWu — APPROVED** [review]
LGTM. Totally didn't test it 😂

**Review by JonasonWu — APPROVED** [review]
LGTM.

**Pull request merged**
